# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ImportIFC
                                 A QGIS plugin
 Dieses Plugin importiert wesentliche Gebäudeattribute aus einer IFC Datei für den City Energy Analyst
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-01-17
        copyright            : (C) 2022 by Marco Kiewit
        email                : marco.kiewit@student.jade-hs.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ImportIFC class from file ImportIFC.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ifc_importer import ImportIFC
    return ImportIFC(iface)
